### ISSUE TITLE
Does PolyCollection support listing hierarchical already saved?

### ISSUE THREAD

**Issue by trondal** [infinite-networks/InfiniteFormBundle#17]
I have a Table Class Hierarchy via Doctrine:

class Order
   protected $products

class Products 
 /*Inheritace class*/

class Car extends Products
class Bus extends Products.

I have all this saved in the database, can I then show *all* these corresponding forms(with populated fields) in one go? Or is this bundle just for creating prototypes for later saving?

**Comment by patie** [comment]
im also interested in
