### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by MelanieLegault** [infinite-networks/InfiniteFormBundle#22]
Hello,

I am trying to install this bundle but I kept getting the following error:
```
[InvalidArgumentException]                                                                                                                                   
  Could not find package infinite-networks/form-bundle at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability 
```
I am using the command as specified 
```php composer.phar require infinite-networks/form-bundle```

I tried to write this command at the dir level where composer files are located as well as inside the subdir of the app, downloading and unziping the source code before doing it. I must be missing something here.

Can't find anything relevant on the web.

Thanks,

**Comment by stof** [comment]
@jmclean @merk any reason to have only alpha releases of this bundle ?

**Comment by MelanieLegault** [comment]
Nope. was that an alpha release? I can surely work with a stable release.

**Comment by merk** [comment]
1.0.0 was tagged yesterday.
