### ISSUE TITLE
Does it work recursivly?

### ISSUE THREAD

**Issue by trondal** [infinite-networks/InfiniteFormBundle#23]
Hi.

Does the polycollection type work when belonging to an collection?
form->collection->ploycollection?

**Comment by merk** [comment]
Yes, theres no reason it wont work except it becomes more complex working with prototypes

**Comment by bokonet** [comment]
A problem work recursivly is, that all javascript `<script type="text/javascript">...</script>` in the prototype will be removed because of `$row = $($.parseHTML(html));`.
can you change that in collections.js to `$row = $($.parseHTML(html,document,true));`?
