### ISSUE TITLE
object pass into polycollection

### ISSUE THREAD

**Issue by patie** [infinite-networks/InfiniteFormBundle#24]
Hi,

how can i pass object from controller/main type into one of / all infinite_form_polycollection children correctly ?

(user entity for example)

thanks

**Comment by chadyred** [comment]
Hey,

it's like me, I have a list of type, and I have an error because I have this :  'rendezVous' => array(array('_type' =>'myapp_mybundle_mytype")) or the type that I want...

Where can I choose the good "type" child of "types" ?

Thank you ! :)
