### ISSUE TITLE
The checkbox grid system must be rewritten to avoid using deprecated Form APIs

### ISSUE THREAD

**Issue by stof** [infinite-networks/InfiniteFormBundle#41]
Currently, this feature relies on several features deprecated in Symfony 2.7 (where the code related to choice lists was rewritten for the most part). This is needed to avoid deprecation warnings on 2.7+ and to be compatible with 3.0

@merk note that I'm not using the checkbox grid system, so I will probably not work on this myself (it might be a significant work to support both the old and new Form APIs to reuse choice lists btw). I'm opening this issue to track the remaining tasks towards eliminating all deprecations warnings (which are making the testsuite fail in #35)

**Comment by merk** [comment]
The only application we have using the grid will be on 2.3 until its EOL. If anyone else is using the checkbox grid, a PR fixing the deprecation warnings would be appreciated.

**Comment by jmclean** [comment]
This is working in 4.2 now
