### ISSUE TITLE
complete code demo

### ISSUE THREAD

**Issue by alexbaron** [infinite-networks/InfiniteFormBundle#66]
Hello,

i try to use this bundle. Is it possible in doc to show a complete example of use. I try to use js event to add  a "polycollection" item but i don't understand how to render prototypes in the view.

thanks.

**Comment by jmclean** [comment]
Can you give https://github.com/infinite-networks/form-demo a look and let me know if it works for you?

**Comment by jmclean** [comment]
Tidying up old issues
