### ISSUE TITLE
Support for Symfony 7.1 possible?

### ISSUE THREAD

**Issue by daFish** [infinite-networks/InfiniteFormBundle#73]
Hello there,

since the release of Symfony 7.1 the class `ResizePolyFormListener` is no longer compatible with `symfony/form` as the base class no longer exposes the needed properties and methods.
I already tried to make the event listener compatible but failed so far. Any hints how to make it work are greatly appreciated.

**Comment by jmclean** [comment]
OK, I have released version 3.4.0 with Symfony 7 support. Symfony changed some fields ($this->type etc.) to private, but I was able to copy their values in the ResizePolyFormListener constructor.

**Comment by daFish** [comment]
Thank you very much, @jmclean. Much appreciated.
